version: '3.8'

services:
  # postgres:
  #   image: postgres:13
  #   environment:
  #     - POSTGRES_USER=admin123
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=my_shop
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
  #     - PGADMIN_DEFAULT_PASSWORD=postgres
  #   ports:
  #     - "5050:80"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000"
  
  mysql:
    image: mysql:5
    environment:
    - MYSQL_DATABASE=my_shop
    - MYSQL_USER=root
    - MYSQL_ROOT_PASSWORD=2215379448Ji
    - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql