version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=admin123
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my_shop
    ports:
      - 5432:5432
    volumes:
     - ./postgres-data:/var/lib/postgresql/data
  
  pgadmin: 
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - 5050:80